version: '3.9'
services:
  postgres-dev:
    image: postgres:16
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=nest-dev
    ports:
      - 5432:5432
  postgres-test:
    image: postgres:16
    container_name: postgres-test
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=nest-test
    ports:
      - 5431:5432
